//! The `todowrite` tool: session-level task list (deepagents `write_todos` semantics,
//! (see `sandbox`).
//!
//! Semantics: **full rewrite** (not an incremental patch) -- the model passes the complete list on every call,
//! replacing the session-level shared state wholesale. `id`s are auto-generated from list position (`"1"..="n"`),
//! and callers do not maintain ids: this matches deepagents' id-less shape, reducing model burden and id drift;
//! position is identity when the list is rewritten wholesale.
//!
//! State-sharing design: the list is session-level state while [`ToolCtx`] is a plain data snapshot
//! (rebuilt every turn), unfit for carrying mutable handles -- the [`TodoStore`] is held by the session config and
//! injected into [`TodoWrite`] at assembly; [`crate::Registry`] only indexes tools and carries no
//! planning / skills session state.

use std::sync::{Arc, RwLock};

use serde_json::{Value, json};

use crate::{Result, Tool, ToolCtx, ToolOutput};

/// Task-list entry cap: stops a runaway model from polluting context and echoed output with an oversized list.
const MAX_TODOS: usize = 100;

/// Task-list entry status (linear three-state, aligned with deepagents).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TodoStatus {
    Pending,
    InProgress,
    Completed,
}

impl TodoStatus {
    /// Parse a status word; invalid values return None (the caller converts that into business-failure output for the model).
    fn parse(raw: &str) -> Option<Self> {
        match raw {
            "pending" => Some(Self::Pending),
            "in_progress" => Some(Self::InProgress),
            "completed" => Some(Self::Completed),
            _ => None,
        }
    }

    /// Status word (used for echo and injected text).
    pub fn label(self) -> &'static str {
        match self {
            Self::Pending => "pending",
            Self::InProgress => "in_progress",
            Self::Completed => "completed",
        }
    }
}

/// Task-list entry. `id` is generated by position (see the module docs); callers only provide content/status.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TodoItem {
    pub id: String,
    pub content: String,
    pub status: TodoStatus,
}

/// Shared handle for the session-level task list (`Arc<RwLock<..>>`; cloning shares).
///
/// Uses `std::sync::RwLock` instead of the tokio variant: the critical section only reads/writes a Vec with no
/// lock held across await, so a sync lock is simpler (same rationale as `ApprovalGate`'s Mutex choice).
#[derive(Debug, Clone, Default)]
pub struct TodoStore {
    inner: Arc<RwLock<Vec<TodoItem>>>,
}

impl TodoStore {
    /// Rewrite the whole list (todowrite semantics).
    pub fn write(&self, items: Vec<TodoItem>) {
        *crate::write(&self.inner) = items;
    }

    /// Current list snapshot.
    pub fn snapshot(&self) -> Vec<TodoItem> {
        crate::read(&self.inner).clone()
    }

    /// Unfinished-item counts `(pending, in_progress)` (stop-steering criterion).
    pub fn unfinished(&self) -> (usize, usize) {
        let items = crate::read(&self.inner);
        let pending = items
            .iter()
            .filter(|i| i.status == TodoStatus::Pending)
            .count();
        let in_progress = items
            .iter()
            .filter(|i| i.status == TodoStatus::InProgress)
            .count();
        (pending, in_progress)
    }
}

/// Numbered echo of the list (shared by tool output / context injection / steering reminders):
/// `1. [pending] content`, one per line. An empty list returns a fixed message.
pub fn format_todos(items: &[TodoItem]) -> String {
    if items.is_empty() {
        return "Task list is empty.".to_owned();
    }
    items
        .iter()
        .map(|i| format!("{}. [{}] {}", i.id, i.status.label(), i.content))
        .collect::<Vec<_>>()
        .join("\n")
}

/// `todowrite`: rewrite the whole session task list (deepagents planning).
pub struct TodoWrite {
    store: TodoStore,
}

impl TodoWrite {
    /// Build with a shared state handle (the same Arc as the [`TodoStore`] in the session config).
    pub fn new(store: TodoStore) -> Self {
        Self { store }
    }
}

#[async_trait::async_trait]
impl Tool for TodoWrite {
    fn name(&self) -> &str {
        "todowrite"
    }

    fn kind(&self) -> wavecode_protocol::ToolKind {
        wavecode_protocol::ToolKind::SessionState
    }

    fn description(&self) -> &str {
        "Replace the session task list (full rewrite, not a patch). Use it to break down \
         complex or multi-step tasks before starting, and to update item status \
         (pending / in_progress / completed) as you make progress. Always provide the \
         complete list; an empty array clears it. The updated list is echoed back."
    }

    fn input_schema(&self) -> Value {
        json!({
            "type": "object",
            "properties": {
                "todos": {
                    "type": "array",
                    "description": "The complete new task list (replaces the current one)",
                    "items": {
                        "type": "object",
                        "properties": {
                            "content": {
                                "type": "string",
                                "description": "Task description"
                            },
                            "status": {
                                "type": "string",
                                "enum": ["pending", "in_progress", "completed"],
                                "description": "Task status"
                            }
                        },
                        "required": ["content", "status"]
                    }
                }
            },
            "required": ["todos"]
        })
    }

    fn is_read_only(&self) -> bool {
        // Mutates session state (the real non-read-only semantics): runs in the serial section so concurrent
        // todowrite calls within one batch cannot race. Approval-wise it passes via the sandbox's session-state
        // exemption (no filesystem writes, no spawned processes); see wavecode-sandbox's is_session_state.
        false
    }

    async fn execute(&self, input: Value, _ctx: &ToolCtx) -> Result<ToolOutput> {
        let err = |reason: String| {
            Ok(ToolOutput {
                content: reason,
                is_error: true,
            })
        };
        let Some(todos) = input.get("todos").and_then(Value::as_array) else {
            return err("missing or invalid parameter 'todos' (array required)".to_owned());
        };
        if todos.len() > MAX_TODOS {
            return err(format!("too many todos: {} (max {MAX_TODOS})", todos.len()));
        }
        let mut items = Vec::with_capacity(todos.len());
        for (i, raw) in todos.iter().enumerate() {
            let Some(content) = raw.get("content").and_then(Value::as_str) else {
                return err(format!(
                    "todos[{i}]: missing or invalid 'content' (string required)"
                ));
            };
            if content.trim().is_empty() {
                return err(format!("todos[{i}]: 'content' must not be empty"));
            }
            let Some(status_raw) = raw.get("status").and_then(Value::as_str) else {
                return err(format!(
                    "todos[{i}]: missing or invalid 'status' (string required)"
                ));
            };
            let Some(status) = TodoStatus::parse(status_raw) else {
                return err(format!(
                    "todos[{i}]: invalid status {status_raw:?} \
                     (expected pending | in_progress | completed)"
                ));
            };
            // ids are auto-generated by position (callers do not maintain ids, see the module docs).
            items.push(TodoItem {
                id: (i + 1).to_string(),
                content: content.to_owned(),
                status,
            });
        }
        self.store.write(items);
        // Echo the current list (numbers + status markers) so the model can confirm the write.
        Ok(ToolOutput {
            content: format!(
                "Task list updated:\n{}",
                format_todos(&self.store.snapshot())
            ),
            is_error: false,
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn ctx() -> ToolCtx {
        ToolCtx {
            cwd: std::path::PathBuf::from("."),
            deny_env: Vec::new(),
        }
    }

    #[tokio::test]
    async fn write_replaces_list_and_echoes() {
        let store = TodoStore::default();
        let tool = TodoWrite::new(store.clone());
        let out = tool
            .execute(
                json!({"todos": [
                    {"content": "Read code", "status": "completed"},
                    {"content": "Write implementation", "status": "in_progress"},
                    {"content": "Run tests", "status": "pending"},
                ]}),
                &ctx(),
            )
            .await
            .unwrap();
        assert!(!out.is_error);
        assert!(out.content.contains("1. [completed] Read code"));
        assert!(
            out.content
                .contains("2. [in_progress] Write implementation")
        );
        assert!(out.content.contains("3. [pending] Run tests"));
        // The shared handle reads the same state; ids are generated by position.
        let snap = store.snapshot();
        assert_eq!(snap.len(), 3);
        assert_eq!(snap[0].id, "1");
        assert_eq!(store.unfinished(), (1, 1));

        // Full rewrite: the second call replaces everything (no old entries kept).
        tool.execute(
            json!({"todos": [{"content": "Wrap up", "status": "pending"}]}),
            &ctx(),
        )
        .await
        .unwrap();
        let snap = store.snapshot();
        assert_eq!(snap.len(), 1);
        assert_eq!(snap[0].content, "Wrap up");
    }

    #[tokio::test]
    async fn empty_array_clears_list() {
        let store = TodoStore::default();
        let tool = TodoWrite::new(store.clone());
        tool.execute(
            json!({"todos": [{"content": "x", "status": "pending"}]}),
            &ctx(),
        )
        .await
        .unwrap();
        let out = tool.execute(json!({"todos": []}), &ctx()).await.unwrap();
        assert!(!out.is_error);
        assert!(out.content.contains("Task list is empty."));
        assert_eq!(store.unfinished(), (0, 0));
    }

    #[tokio::test]
    async fn invalid_input_is_error_output_not_panic() {
        let tool = TodoWrite::new(TodoStore::default());
        // Missing todos.
        assert!(tool.execute(json!({}), &ctx()).await.unwrap().is_error);
        // Invalid status.
        let out = tool
            .execute(
                json!({"todos": [{"content": "x", "status": "done"}]}),
                &ctx(),
            )
            .await
            .unwrap();
        assert!(out.is_error);
        assert!(out.content.contains("invalid status"));
        // Empty content.
        assert!(
            tool.execute(
                json!({"todos": [{"content": "  ", "status": "pending"}]}),
                &ctx()
            )
            .await
            .unwrap()
            .is_error
        );
        // Missing content / status.
        assert!(
            tool.execute(json!({"todos": [{"status": "pending"}]}), &ctx())
                .await
                .unwrap()
                .is_error
        );
        // Over the cap.
        let many: Vec<Value> = (0..=MAX_TODOS)
            .map(|i| json!({"content": format!("t{i}"), "status": "pending"}))
            .collect();
        assert!(
            tool.execute(json!({"todos": many}), &ctx())
                .await
                .unwrap()
                .is_error
        );
    }
}
