[package]
name = "state-checkpoint"
edition.workspace = true
rust-version.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
thiserror.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
wavecode-config = { path = "../../foundation/config" }

[dev-dependencies]
tempfile.workspace = true
