//! wavecode-protocol - the single source of truth for the frontend-backend protocol.
//!
//! Defines `Submission { id, op: Op }` (frontend -> core requests) and
//! `Event { id, msg: EventMsg }` (core -> frontend event stream); id links one
//! request to all of its follow-up events. `Op` / `EventMsg` are marked `#[non_exhaustive]`
//! so the protocol can evolve backward-compatibly.
//!
//! All Rust crates and frontends (TUI / Web / Desktop) share this protocol;
//! the TypeScript-side types are exported from here by `wavecode app-server generate-ts` (planned,
//! landing in a later milestone).

use serde::{Deserialize, Serialize};

/// One frontend -> core request; id is generated by the frontend (uuid) and links all follow-up events
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct Submission {
    pub id: String,
    pub op: Op,
}

/// A frontend -> core operation (the `Submission.op` payload; the wire format is locked by serde tags).
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(tag = "type", rename_all = "snake_case")]
#[non_exhaustive]
pub enum Op {
    UserInput {
        text: String,
    },
    Interrupt,
    /// Approval reply (SPEC section 12): answers the in-flight `ApprovalRequested`, linked by call_id.
    ExecApproval {
        call_id: String,
        decision: ApprovalDecision,
    },
    /// Switches the session-level permission mode (SPEC section 12).
    SetPermissionMode {
        mode: PermissionMode,
    },
    /// Compacts context immediately (`/compact`, SPEC section 6): runs directly when no turn is active;
    /// while a turn is running, the driver queues it until the turn ends.
    Compact,
    /// Direct skill invocation via slash (`/name [args]`, SPEC sections 4.1 / 8.2, landed in P7):
    /// runs directly when no turn is active; queues until the turn ends while a turn is running.
    SlashCommand {
        /// The skill name.
        name: String,
        /// Call arguments (the `$ARGUMENTS` expansion source; may be empty).
        args: String,
    },
    /// Requests the persistent memory index (the `/memory` read surface as protocol): core replies with
    /// `EventMsg::MemoryIndex`. Frontends never read memory files directly - Web/Desktop stay
    /// at parity with the TUI (SPEC section 3, rule 2).
    MemoryList,
    Shutdown,
}

/// Permission mode (SPEC section 12; wire strings match config's `permission_mode`).
///
/// Lives in protocol rather than sandbox: it is the wire type of `Op::SetPermissionMode`,
/// same as `StopReason`; sandbox only holds the decision logic and depends on this type.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[non_exhaustive]
pub enum PermissionMode {
    /// Write / exec / destructive tools need per-call approval (hits on allow rules skip approval).
    #[serde(rename = "default")]
    Default,
    /// Only read-only tools are usable; non-read-only tools are denied straight back into the model.
    #[serde(rename = "plan")]
    Plan,
    /// File edits (write_file / edit_file) auto-approve; shell and friends still need approval.
    #[serde(rename = "acceptEdits")]
    AcceptEdits,
    /// Approve everything (deny rules still apply).
    // TODO(post-P2): entering this mode requires a confirmation phrase (SPEC section 12); frontend interaction waits on the TUI.
    #[serde(rename = "bypassPermissions")]
    BypassPermissions,
}

impl PermissionMode {
    /// Parses a mode string from config / the frontend (same names as the serde wire form).
    pub fn parse(s: &str) -> Option<Self> {
        match s {
            "default" => Some(Self::Default),
            "plan" => Some(Self::Plan),
            "acceptEdits" => Some(Self::AcceptEdits),
            "bypassPermissions" => Some(Self::BypassPermissions),
            _ => None,
        }
    }

    /// Wire string (shared by config and display).
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Default => "default",
            Self::Plan => "plan",
            Self::AcceptEdits => "acceptEdits",
            Self::BypassPermissions => "bypassPermissions",
        }
    }
}

impl std::fmt::Display for PermissionMode {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

/// Approval decision (the `Op::ExecApproval.decision` payload; the wire format is locked by serde tags).
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(tag = "type", rename_all = "snake_case")]
#[non_exhaustive]
pub enum ApprovalDecision {
    /// Approve this once (only the current tool call).
    AllowOnce,
    /// Approve always: approves this call and derives a precise session-level allow rule from
    /// its shape (later same-shape calls skip approval). The rule lives on the in-memory `Sandbox`
    /// instance; config-file persistence hooks up once layered config (section 17.5 M3) lands.
    AllowAlways,
    /// Deny; the reason goes back into the model (may be empty, core fills a default message).
    Deny { reason: String },
}

/// Approval kind (the `EventMsg::ApprovalRequested.kind`), letting the frontend pick a display shape.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
#[non_exhaustive]
pub enum ApprovalKind {
    /// Shell command execution.
    Exec,
    /// File write / edit.
    Write,
}

/// A core -> frontend event; id echoes the matching Submission.id
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct Event {
    pub id: String,
    pub msg: EventMsg,
}

/// A core -> frontend event message (the `Event.msg` payload; the wire format is locked by serde tags).
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(tag = "type", rename_all = "snake_case")]
#[non_exhaustive]
pub enum EventMsg {
    TurnStarted {
        turn_id: String,
    },
    AgentMessageDelta {
        text: String,
    },
    AgentMessageComplete {
        text: String,
    },
    ToolCallBegin {
        call_id: String,
        tool: String,
        input: serde_json::Value,
    },
    ToolCallEnd {
        call_id: String,
        ok: bool,
        output: String,
    },
    /// A destructive / non-read-only tool needs human approval (SPEC section 12): the frontend shows detail,
    /// then replies with the decision via `Op::ExecApproval` (same call_id).
    ApprovalRequested {
        call_id: String,
        kind: ApprovalKind,
        detail: String,
    },
    TokenCount {
        used: u64,
        window: u64,
    },
    /// Context compaction started (SPEC section 6; `trigger` tells the three auto triggers apart from manual `/compact`).
    CompactStarted {
        trigger: CompactTrigger,
    },
    /// Context compaction finished; `summary_tokens` estimates the summary message's tokens.
    CompactCompleted {
        summary_tokens: u64,
    },
    /// Subagent spawned (P5, SPEC section 5.3): emitted when the task tool spawns a subagent
    /// (both background and synchronous forms emit it); the subagent's intermediate progress never enters
    /// the parent session event stream (an isomorphic of context isolation) - the frontend only sees start and end.
    SubagentStarted {
        task_id: String,
        subagent_type: String,
        description: String,
    },
    /// A subagent reached its terminal state (completed / failed / stopped); `summary` is the final text summary
    /// (an error summary on failure), from the same source as the `<task-notification>` re-injected into the parent session.
    SubagentCompleted {
        task_id: String,
        status: SubagentStatus,
        summary: String,
    },
    Warning {
        message: String,
    },
    /// The reply to `Op::MemoryList`: the persistent memory index (the `/memory` read surface).
    /// A `None` `path` means the session has no memory attached (capability unavailable); a missing
    /// index file is the normal shape, with `content` as an empty string.
    MemoryIndex {
        /// Index file path (for display; `None` = no memory attached).
        path: Option<String>,
        /// Full index text (missing = empty string).
        content: String,
    },
    Error {
        message: String,
        recoverable: bool,
    },
    TurnCompleted {
        stop_reason: StopReason,
    },
}

/// Subagent terminal state (the `EventMsg::SubagentCompleted.status`, P5).
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
#[non_exhaustive]
pub enum SubagentStatus {
    /// Completed normally (the turn ended in end_turn or another terminal state).
    Completed,
    /// Failed (the turn errored; summary is the error summary).
    Failed,
    /// Stopped by task_stop (the turn ended as Interrupted).
    Stopped,
}

/// Compaction trigger source (the `EventMsg::CompactStarted.trigger`).
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
#[non_exhaustive]
pub enum CompactTrigger {
    /// Auto-compaction path (PreTurn budget check, SPEC section 6).
    Auto,
    /// Blocking path (compaction forced before sampling).
    Blocking,
    /// reactive compact: a compaction retry triggered by `prompt_too_long`-class errors (SPEC section 5.2).
    Reactive,
    /// Manual `/compact` (Op::Compact).
    Manual,
}

/// Turn end reason (the `EventMsg::TurnCompleted.stop_reason`).
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
#[non_exhaustive]
pub enum StopReason {
    Completed,
    Interrupted,
    Error,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn submission_roundtrip() {
        let sub = Submission {
            id: "s-1".into(),
            op: Op::UserInput {
                text: "hello".into(),
            },
        };
        let json = serde_json::to_string(&sub).unwrap();
        assert_eq!(
            json,
            r#"{"id":"s-1","op":{"type":"user_input","text":"hello"}}"#
        );
        assert_eq!(serde_json::from_str::<Submission>(&json).unwrap(), sub);
    }

    #[test]
    fn event_roundtrip_tool_call() {
        let ev = Event {
            id: "s-1".into(),
            msg: EventMsg::ToolCallBegin {
                call_id: "c1".into(),
                tool: "read_file".into(),
                input: serde_json::json!({"path": "a.txt"}),
            },
        };
        let json = serde_json::to_string(&ev).unwrap();
        assert_eq!(serde_json::from_str::<Event>(&json).unwrap(), ev);
    }

    #[test]
    fn wire_type_tags_locked() {
        // Locks the protocol wire format: the exact "type" tag of each variant (SPEC section 4.1).
        // New variants must be registered in the table; changing an existing tag breaks wire compat.
        let op_cases: [(Op, &str); 8] = [
            (Op::UserInput { text: "t".into() }, "user_input"),
            (Op::Interrupt, "interrupt"),
            (
                Op::ExecApproval {
                    call_id: "c".into(),
                    decision: ApprovalDecision::AllowOnce,
                },
                "exec_approval",
            ),
            (
                Op::SetPermissionMode {
                    mode: PermissionMode::Default,
                },
                "set_permission_mode",
            ),
            (Op::Compact, "compact"),
            (
                Op::SlashCommand {
                    name: "commit".into(),
                    args: "a".into(),
                },
                "slash_command",
            ),
            (Op::Shutdown, "shutdown"),
            (Op::MemoryList, "memory_list"),
        ];
        for (op, tag) in op_cases {
            let json = serde_json::to_string(&op).unwrap();
            assert!(
                json.contains(&format!(r#""type":"{tag}""#)),
                "Op::{tag} type tag drifted: {json}"
            );
        }

        let event_cases: [(EventMsg, &str); 15] = [
            (
                EventMsg::TurnStarted {
                    turn_id: "t1".into(),
                },
                "turn_started",
            ),
            (
                EventMsg::AgentMessageDelta { text: "t".into() },
                "agent_message_delta",
            ),
            (
                EventMsg::AgentMessageComplete { text: "t".into() },
                "agent_message_complete",
            ),
            (
                EventMsg::ToolCallBegin {
                    call_id: "c".into(),
                    tool: "read_file".into(),
                    input: serde_json::json!({}),
                },
                "tool_call_begin",
            ),
            (
                EventMsg::ToolCallEnd {
                    call_id: "c".into(),
                    ok: true,
                    output: "o".into(),
                },
                "tool_call_end",
            ),
            (
                EventMsg::ApprovalRequested {
                    call_id: "c".into(),
                    kind: ApprovalKind::Write,
                    detail: "d".into(),
                },
                "approval_requested",
            ),
            (EventMsg::TokenCount { used: 1, window: 2 }, "token_count"),
            (
                EventMsg::CompactStarted {
                    trigger: CompactTrigger::Auto,
                },
                "compact_started",
            ),
            (
                EventMsg::CompactCompleted { summary_tokens: 7 },
                "compact_completed",
            ),
            (
                EventMsg::SubagentStarted {
                    task_id: "task-1".into(),
                    subagent_type: "explore".into(),
                    description: "d".into(),
                },
                "subagent_started",
            ),
            (
                EventMsg::SubagentCompleted {
                    task_id: "task-1".into(),
                    status: SubagentStatus::Completed,
                    summary: "s".into(),
                },
                "subagent_completed",
            ),
            (
                EventMsg::Warning {
                    message: "w".into(),
                },
                "warning",
            ),
            (
                EventMsg::MemoryIndex {
                    path: Some("/root/.wavecode/memory/MEMORY.md".into()),
                    content: "- [note](x.md)".into(),
                },
                "memory_index",
            ),
            (
                EventMsg::Error {
                    message: "e".into(),
                    recoverable: true,
                },
                "error",
            ),
            (
                EventMsg::TurnCompleted {
                    stop_reason: StopReason::Completed,
                },
                "turn_completed",
            ),
        ];
        for (msg, tag) in event_cases {
            let json = serde_json::to_string(&msg).unwrap();
            assert!(
                json.contains(&format!(r#""type":"{tag}""#)),
                "EventMsg::{tag} type tag drifted: {json}"
            );
        }

        // Lock the full StopReason snake_case set
        let reason_cases: [(StopReason, &str); 3] = [
            (StopReason::Completed, "completed"),
            (StopReason::Interrupted, "interrupted"),
            (StopReason::Error, "error"),
        ];
        for (reason, tag) in reason_cases {
            let json = serde_json::to_string(&reason).unwrap();
            assert_eq!(json, format!(r#""{tag}""#), "StopReason tag drifted");
        }

        // Lock the PermissionMode wire form (matches the config `permission_mode` strings;
        // note acceptEdits / bypassPermissions are camelCase, not snake_case).
        let mode_cases: [(PermissionMode, &str); 4] = [
            (PermissionMode::Default, "default"),
            (PermissionMode::Plan, "plan"),
            (PermissionMode::AcceptEdits, "acceptEdits"),
            (PermissionMode::BypassPermissions, "bypassPermissions"),
        ];
        for (mode, tag) in mode_cases {
            let json = serde_json::to_string(&mode).unwrap();
            assert_eq!(json, format!(r#""{tag}""#), "PermissionMode tag drifted");
            assert_eq!(PermissionMode::parse(tag), Some(mode));
            assert_eq!(mode.to_string(), tag);
        }
        assert_eq!(PermissionMode::parse("Default"), None);

        // Lock the ApprovalDecision / ApprovalKind wire forms
        let decision_cases: [(ApprovalDecision, &str); 3] = [
            (ApprovalDecision::AllowOnce, r#"{"type":"allow_once"}"#),
            (ApprovalDecision::AllowAlways, r#"{"type":"allow_always"}"#),
            (
                ApprovalDecision::Deny { reason: "r".into() },
                r#"{"type":"deny","reason":"r"}"#,
            ),
        ];
        for (decision, json) in decision_cases {
            assert_eq!(
                serde_json::to_string(&decision).unwrap(),
                json,
                "ApprovalDecision wire form drifted"
            );
        }
        let kind_cases: [(ApprovalKind, &str); 2] =
            [(ApprovalKind::Exec, "exec"), (ApprovalKind::Write, "write")];
        for (kind, tag) in kind_cases {
            let json = serde_json::to_string(&kind).unwrap();
            assert_eq!(json, format!(r#""{tag}""#), "ApprovalKind tag drifted");
        }

        // Lock the CompactTrigger wire form (P3)
        let trigger_cases: [(CompactTrigger, &str); 4] = [
            (CompactTrigger::Auto, "auto"),
            (CompactTrigger::Blocking, "blocking"),
            (CompactTrigger::Reactive, "reactive"),
            (CompactTrigger::Manual, "manual"),
        ];
        for (trigger, tag) in trigger_cases {
            let json = serde_json::to_string(&trigger).unwrap();
            assert_eq!(json, format!(r#""{tag}""#), "CompactTrigger tag drifted");
        }

        // Lock the SubagentStatus wire form (P5)
        let status_cases: [(SubagentStatus, &str); 3] = [
            (SubagentStatus::Completed, "completed"),
            (SubagentStatus::Failed, "failed"),
            (SubagentStatus::Stopped, "stopped"),
        ];
        for (status, tag) in status_cases {
            let json = serde_json::to_string(&status).unwrap();
            assert_eq!(json, format!(r#""{tag}""#), "SubagentStatus tag drifted");
        }
    }

    #[test]
    fn turn_completed_wire_format_locked() {
        // Lock the protocol wire format: the exact JSON rendering of the type tag and nested stop_reason
        let ev = Event {
            id: "s-1".into(),
            msg: EventMsg::TurnCompleted {
                stop_reason: StopReason::Completed,
            },
        };
        let msg_json = serde_json::to_string(&ev.msg).unwrap();
        assert_eq!(
            msg_json,
            r#"{"type":"turn_completed","stop_reason":"completed"}"#
        );
        // the nested structure inside msg stays unchanged once wrapped in an Event
        let json = serde_json::to_string(&ev).unwrap();
        assert_eq!(
            json,
            r#"{"id":"s-1","msg":{"type":"turn_completed","stop_reason":"completed"}}"#
        );
        assert_eq!(serde_json::from_str::<Event>(&json).unwrap(), ev);
    }
}
